cpu_docker_builder:    
  timeout_in: 120m
  env:
    DOCKERHUB_USER: ENCRYPTED[5bc8a91d5b3ea9e9a45a91d3b836a2b60bf6776587f02408982786213b4b1b19f54089007a8266f93f6e0a44015cb509]
    DOCKERHUB_PASS: ENCRYPTED[c19a2ef9ce4a1ab8d33f76c43b68c3a745496b93dcfaa2af724abfaa1d021ee3a0ceb8d2064f00c4117ef90d20c64465]
  script: |
    docker info
    export TAG=${CIRRUS_TAG:-latest}
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG} .
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}
